#docker-compose.yml
services:
  cargoflow.identity.api:
    image: ${DOCKER_REGISTRY-}cargoflowidentityapi
    build:
      context: .
      dockerfile: Src/Identity/CargoFlow.Identity.Api/Dockerfile
  identitydb:
    image: postgres:16.4
  keycloak:
    image: quay.io/keycloak/keycloak:26.0

volumes:
  postgres_identity:

networks:
  cargoflow:  
    driver: bridge
