services:

  identitydb:
    container_name: identitydb
    image: postgres:16.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cargoflow_identity
    ports:
      - "5432:5432"
    volumes:
      - postgres_identity:/var/lib/postgresql/data
    networks:
      - cargoflow



  cargoflow.identity.api:
    container_name: identity-api
    depends_on:
      - identitydb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__IdentityDatabase=Host=identitydb;Port=5432;Database=cargoflow_identity;Username=postgres;Password=postgres

    ports:
      - "5001:8080"

    networks:
      - cargoflow